<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <StartupObject>AEC1001.Program</StartupObject>
    <ApplicationIcon>B032_AEC1001.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="B032_AEC1001.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoCAD.NET" Version="26.0.0" />
    <PackageReference Include="AutoCAD.NET.Core" Version="26.0.0" />
    <PackageReference Include="AutoCAD.NET.Model" Version="26.0.0" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoCAD.NET" Version="25.0.0" ExcludeAssets="runtime" />
	</ItemGroup>

</Project>